package com.aimpl.domain.archive.service;

import com.aimpl.common.exception.BizException;
import com.aimpl.domain.archive.codegen.ProductCodeGenerator;
import com.aimpl.domain.archive.codegen.SpecParams;
import com.aimpl.domain.archive.codegen.SpecParser;
import com.aimpl.domain.archive.dto.ProductCreateDTO;
import com.aimpl.domain.archive.entity.Product;
import com.aimpl.domain.archive.entity.ProductCategory;
import com.aimpl.domain.archive.mapper.ProductMapper;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
public class ProductService extends ServiceImpl<ProductMapper, Product> {

    private final ProductCategoryService categoryService;

    @Transactional
    public Product createProduct(ProductCreateDTO dto) {
        ProductCategory category = categoryService.getById(dto.getCategoryId());
        if (category == null) {
            throw new BizException("货品类别不存在: " + dto.getCategoryId());
        }

        Product product = new Product();
        product.setProductName(dto.getProductName());
        product.setSpec(dto.getSpec());
        product.setMaterial(dto.getMaterial());
        product.setSteelMill(dto.getSteelMill());
        product.setSurface(dto.getSurface());
        product.setCategoryId(dto.getCategoryId());
        product.setUnit(dto.getUnit());
        product.setPricingUnit(dto.getPricingUnit());
        product.setTaxRate(dto.getTaxRate());
        product.setEnabled(true);

        if (dto.getProductCode() != null && !dto.getProductCode().isBlank()) {
            validateCodeUnique(dto.getProductCode(), null);
            product.setProductCode(dto.getProductCode());
            product.setCodeAutoGenerated(false);
        } else {
            String code = generateCode(category, dto.getSpec());
            product.setProductCode(code);
            product.setCodeAutoGenerated(true);
        }

        validateProductUnique(product);
        save(product);
        return product;
    }

    private String generateCode(ProductCategory category, String spec) {
        if (category.getCategoryGroup() == null) {
            throw new BizException("品类 [" + category.getCategoryName()
                    + "] 未设置分组(categoryGroup)，无法自动生成编码");
        }

        SpecParams params = SpecParser.parse(category.getCategoryGroup(), spec);

        int seq = 1;
        if (category.getCategoryGroup()
                == com.aimpl.common.enums.ProductCategoryGroup.NON_STEEL) {
            Long maxCount = lambdaQuery()
                    .eq(Product::getCategoryId, category.getId())
                    .count();
            seq = maxCount.intValue() + 1;
        }

        String code = ProductCodeGenerator.generate(
                category.getCategoryCode(), category.getCategoryGroup(), params, seq);

        if (codeExists(code)) {
            code = code + "A";
        }
        return code;
    }

    private boolean codeExists(String code) {
        return count(new LambdaQueryWrapper<Product>()
                .eq(Product::getProductCode, code)) > 0;
    }

    private void validateCodeUnique(String code, Long excludeId) {
        LambdaQueryWrapper<Product> qw = new LambdaQueryWrapper<Product>()
                .eq(Product::getProductCode, code);
        if (excludeId != null) {
            qw.ne(Product::getId, excludeId);
        }
        if (count(qw) > 0) {
            throw new BizException("货品编码已存在: " + code);
        }
    }

    private void validateProductUnique(Product product) {
        boolean dup = count(new LambdaQueryWrapper<Product>()
                .eq(Product::getProductName, product.getProductName())
                .eq(Product::getSpec, product.getSpec())
                .eq(Product::getMaterial, product.getMaterial())
                .eq(Product::getSteelMill, product.getSteelMill())
                .ne(product.getId() != null, Product::getId, product.getId())
        ) > 0;
        if (dup) {
            throw new BizException("货品已存在(品名+规格+材质+钢厂重复): "
                    + product.getProductName() + " " + product.getSpec());
        }
    }
}
