package com.aimpl.domain.project.service;

import com.aimpl.common.exception.BizException;
import com.aimpl.domain.project.dto.PlanGenerateRequestDTO;
import com.aimpl.domain.project.dto.ProjectPlanCreateDTO;
import com.aimpl.domain.project.entity.ProjectPlan;
import com.aimpl.domain.project.mapper.ProjectMapper;
import com.aimpl.domain.project.mapper.ProjectPlanMapper;
import com.aimpl.domain.project.vo.GeneratedPlanVO;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@RequiredArgsConstructor
public class ProjectPlanService extends ServiceImpl<ProjectPlanMapper, ProjectPlan> {

    private final ProjectMapper projectMapper;
    private final ObjectMapper objectMapper;

    @Transactional
    public ProjectPlan createPlan(ProjectPlanCreateDTO dto) {
        if (projectMapper.selectById(dto.getProjectId()) == null) {
            throw new BizException("项目不存在: " + dto.getProjectId());
        }

        if (count(new LambdaQueryWrapper<ProjectPlan>()
                .eq(ProjectPlan::getProjectId, dto.getProjectId())) > 0) {
            throw new BizException("该项目已存在计划");
        }

        ProjectPlan plan = new ProjectPlan();
        plan.setProjectId(dto.getProjectId());
        plan.setPlanName(dto.getPlanName());
        plan.setTotalDays(dto.getTotalDays());
        plan.setMilestones(dto.getMilestones());
        plan.setWbsItems(dto.getWbsItems());
        plan.setResources(dto.getResources());
        plan.setRisks(dto.getRisks());
        plan.setStatus(dto.getStatus() != null ? dto.getStatus() : "DRAFT");
        save(plan);
        return plan;
    }

    public List<ProjectPlan> listByProject(Long projectId) {
        return list(new LambdaQueryWrapper<ProjectPlan>()
                .eq(ProjectPlan::getProjectId, projectId));
    }

    @Transactional
    public ProjectPlan saveGeneratedPlan(Long projectId, GeneratedPlanVO vo, PlanGenerateRequestDTO request) {
        ProjectPlan plan = new ProjectPlan();
        plan.setProjectId(projectId);
        plan.setPlanName("AI自动生成计划");
        plan.setTotalDays(vo.getEstimatedDurationDays());
        plan.setMilestones(toJson(vo.getMilestones()));
        plan.setWbsItems(toJson(vo.getWbsItems()));
        plan.setResources(toJson(vo.getResourcePlan()));
        plan.setRisks(toJson(vo.getRiskPlan()));
        plan.setGanttData(toJson(vo.getGanttData()));
        plan.setRiskLevel(vo.getRiskLevel());
        plan.setAutoGenerated(true);
        plan.setStatus("DRAFT");

        if (request.getCustomizationLevel() != null) {
            plan.setCustomizationLevel(request.getCustomizationLevel());
        }
        if (request.getDeadline() != null) {
            plan.setDeadline(request.getDeadline());
        }
        if (request.getBudget() != null) {
            plan.setBudget(request.getBudget());
        }
        if (request.getIntegrationRequirements() != null && !request.getIntegrationRequirements().isEmpty()) {
            plan.setIntegrationRequirements(String.join(",", request.getIntegrationRequirements()));
        }

        save(plan);
        return plan;
    }

    public GeneratedPlanVO getGeneratedPlanDetail(Long planId) {
        ProjectPlan plan = getById(planId);
        if (plan == null) {
            throw new BizException("计划不存在: " + planId);
        }

        GeneratedPlanVO vo = new GeneratedPlanVO();
        vo.setEstimatedDurationDays(plan.getTotalDays() != null ? plan.getTotalDays() : 0);
        vo.setRiskLevel(plan.getRiskLevel());
        vo.setMilestones(fromJson(plan.getMilestones(), new TypeReference<>() {}));
        vo.setWbsItems(fromJson(plan.getWbsItems(), new TypeReference<>() {}));
        vo.setResourcePlan(fromJson(plan.getResources(), new TypeReference<>() {}));
        vo.setRiskPlan(fromJson(plan.getRisks(), new TypeReference<>() {}));
        vo.setGanttData(fromJson(plan.getGanttData(), new TypeReference<>() {}));
        return vo;
    }

    private String toJson(Object obj) {
        if (obj == null) return null;
        try {
            return objectMapper.writeValueAsString(obj);
        } catch (JsonProcessingException e) {
            throw new BizException("JSON序列化失败: " + e.getMessage());
        }
    }

    private <T> T fromJson(String json, TypeReference<T> typeRef) {
        if (json == null || json.isBlank()) return null;
        try {
            return objectMapper.readValue(json, typeRef);
        } catch (JsonProcessingException e) {
            throw new BizException("JSON反序列化失败: " + e.getMessage());
        }
    }
}
