package com.aimpl.domain.report.entity;

import com.aimpl.common.enums.ReportStatus;
import com.aimpl.common.enums.ReportType;
import com.baomidou.mybatisplus.annotation.*;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@TableName("t_delivery_report")
public class DeliveryReport {

    @TableId(type = IdType.AUTO)
    private Long id;

    private Long projectId;

    private ReportType reportType;

    private String title;

    private BigDecimal trainingPassRate;

    private BigDecimal dataImportCompletionRate;

    private Integer totalIssues;

    private Integer resolvedIssues;

    private BigDecimal customerSatisfactionScore;

    private BigDecimal scheduleDeviationPercent;

    private BigDecimal documentCompletionRate;

    private BigDecimal overallScore;

    private String aiComment;

    private String reportContent;

    private Boolean autoGenerated;

    private ReportStatus status;

    private String confirmedBy;

    private LocalDateTime confirmedAt;

    @TableField(fill = FieldFill.INSERT)
    private LocalDateTime createTime;

    @TableField(fill = FieldFill.INSERT_UPDATE)
    private LocalDateTime updateTime;

    @TableLogic
    private Integer deleted;
}
