export interface R<T> {
  code: number
  message: string
  data: T
}

export interface Project {
  id: number
  projectCode: string
  customerName: string
  industryType: string
  scale: string
  pmId: number
  status: string
  modules: string
  region: string
  startDate: string
  endDate: string
  remark: string
  createTime: string
}

export interface ProductCategory {
  id: number
  categoryCode: string
  categoryName: string
  parentId: number | null
  level: number
  sortOrder: number
  categoryGroup: string
  defaultUnit: string
  enabled: boolean
}

export interface Product {
  id: number
  productCode: string
  productName: string
  spec: string
  material: string
  steelMill: string
  surface: string
  categoryId: number
  unit: string
  pricingUnit: string
  taxRate: number
  enabled: boolean
  codeAutoGenerated: boolean
  createTime: string
}

export interface Customer {
  id: number
  customerCode: string
  fullName: string
  shortName: string
  customerType: string
  creditCode: string
  contact: string
  phone: string
  province: string
  city: string
  district: string
  address: string
  category: string
  settlementMethod: string
  creditLimit: number
  taxRate: number
  salesRepId: number
  enabled: boolean
  createTime: string
}

export interface ExamRecord {
  id: number
  projectId: number
  traineeId: number
  module: string
  examType: string
  score: number
  passed: boolean
  requiredCourse: boolean
  weakPoints: string
  retryOf: number | null
  examTime: string
}

export interface GoLiveCheck {
  projectId: number
  goLiveReady: boolean
  message: string
}

export type IndustryType = 'STEEL_TRADER' | 'STEEL_MILL' | 'PROCESSING_CENTER' | 'INTEGRATED_SERVICE'

export const IndustryTypeLabels: Record<IndustryType, string> = {
  STEEL_TRADER: '钢贸商',
  STEEL_MILL: '钢厂',
  PROCESSING_CENTER: '加工中心',
  INTEGRATED_SERVICE: '综合服务商',
}

export const ProjectStatusLabels: Record<string, string> = {
  PENDING: '待启动',
  RESEARCH: '调研中',
  PLAN: '计划中',
  TRAINING: '培训中',
  DATA_IMPORT: '数据导入',
  GO_LIVE: '上线中',
  FOLLOW_UP: '跟进辅助',
  DELIVERED: '已交付',
  AFTER_SALES: '售后阶段',
}

export interface CustomerProfile {
  id: number
  projectId: number
  companyName: string
  legalPerson: string
  registeredCapital: string
  establishmentDate: string
  address: string
  industryType: string
  businessModel: string
  tradeMode: string
  tradeScope: string
  mainBusiness: string
  salesMode: string
  totalProductionLines: number
  productionShifts: string
  mesCurrentStatus: string
  qualityStandards: string
  totalWarehouseCount: number
  totalWarehouseAreaSqm: number
  totalCraneCount: number
  inventoryTurnoverRate: number
  inventoryManagementMethod: string
  monthlyVolume: number
  monthlyAmount: number
  pricingModel: string
  settlementMethods: string
  creditPolicy: string
  totalCustomerCount: number
  customerTypes: string
  topCustomers: string
  totalStaff: number
  departments: string
  keyPositions: string
  decisionChain: string
  existingSystems: string
  targetModules: string
  modulePriorities: string
  managementGoals: string
  processGoals: string
  efficiencyGoals: string
  riskControlGoals: string
}

export interface AccountSet {
  id: number
  projectId: number
  setName: string
  accountingSystem: string
  pricingMethod: string
  qtyDecimals: number
  wgtDecimals: number
  prcDecimals: number
  amtDecimals: number
  useWeight: boolean
  currency: string
  fiscalYearStart: number
  status: string
}

export interface DeliveryReport {
  id: number
  projectId: number
  reportType: string
  title: string
  trainingPassRate: number
  dataImportCompletionRate: number
  totalIssues: number
  resolvedIssues: number
  customerSatisfactionScore: number
  scheduleDeviationPercent: number
  documentCompletionRate: number
  overallScore: number
  aiComment: string
  autoGenerated: boolean
  status: string
  confirmedBy: string
  confirmedAt: string
}

export interface Engineer {
  id: number
  engineerCode: string
  name: string
  level: string
  skills: string
  currentStatus: string
  currentProjectId: number | null
  joinDate: string
  phone: string
  email: string
  compositeScore: number
  monthlyIdleRate: number
  monthlyProjectCount: number
}

export interface ProjectEvaluation {
  id: number
  projectId: number
  evaluatorId: number
  scheduleScore: number
  qualityScore: number
  csatScore: number
  processScore: number
  costScore: number
  pqiScore: number
  rating: string
  aiComment: string
}

export interface ServerProfile {
  id: number
  projectId: number
  serverName: string
  host: string
  port: number
  dbType: string
  dbName: string
  sslEnabled: boolean
  osType: string
  erpVersion: string
  apiBaseUrl: string
  status: string
  lastHealthCheck: string
  networkLatencyMs: number
}

export interface GoLiveCheckItem {
  id: number
  projectId: number
  category: string
  itemName: string
  description: string
  checkResult: string
  detail: string
  checkedAt: string
  checkedBy: string
}

export interface SimulationScene {
  id: number
  projectId: number
  sceneName: string
  sceneType: string
  description: string
  steps: string
  expectedResult: string
  actualResult: string
  status: string
  executedAt: string
  executedBy: string
  deviation: string
}

export const EngineerLevelLabels: Record<string, string> = {
  INTERN: '实习',
  JUNIOR: '初级实施',
  MIDDLE: '中级实施',
  SENIOR: '高级实施',
  PM: 'PM',
  SENIOR_PM: '高级PM',
  EXPERT_PM: '资深PM',
}

export const EngineerStatusLabels: Record<string, string> = {
  IDLE: '空闲',
  ON_PROJECT: '在项目',
  TRAINING: '培训中',
  LEAVE: '请假',
}

export const EvalRatingLabels: Record<string, string> = {
  EXCELLENT: '卓越',
  GOOD: '优良',
  QUALIFIED: '合格',
  NEEDS_IMPROVEMENT: '待改进',
  UNQUALIFIED: '不合格',
}

export const CheckResultLabels: Record<string, string> = {
  PASS: '通过',
  FAIL: '未通过',
  WARNING: '警告',
  UNCHECKED: '未检查',
}

export const SimulationStatusLabels: Record<string, string> = {
  PENDING: '待执行',
  RUNNING: '执行中',
  PASSED: '通过',
  FAILED: '未通过',
}

export interface Supplier {
  id: number
  supplierCode: string
  fullName: string
  shortName: string
  supplierType: string
  creditCode: string
  contact: string
  phone: string
  address: string
  settlementMethod: string
  taxRate: number
  enabled: boolean
}

export interface Warehouse {
  id: number
  warehouseCode: string
  warehouseName: string
  warehouseType: string
  warehouseNature: string
  managementMode: string
  address: string
  contact: string
  phone: string
  areaSqm: number
  craneCount: number
  enabled: boolean
}

export interface RelatedUnit {
  id: number
  unitCode: string
  fullName: string
  unitType: string
  creditCode: string
  contactPerson: string
  phone: string
  address: string
  bankName: string
  bankAccount: string
  enabled: boolean
}

export interface TraineeProfile {
  id: number
  projectId: number
  employeeName: string
  role: string
  department: string
  kaUser: boolean
  progressPercent: number
  attendanceDays: number
  totalDays: number
  riskLevel: string
}

export interface TrainingDailyLog {
  id: number
  projectId: number
  logDate: string
  topic: string
  trainerName: string
  attendeeCount: number
  signInCompleted: boolean
  coursewareUploaded: boolean
  summaryUploaded: boolean
  examConducted: boolean
  dailyReportSubmitted: boolean
  issues: string
}

export interface EngineerWorklog {
  id: number
  engineerId: number
  projectId: number
  workDate: string
  tasksPlan: string
  tasksCompleted: string
  documentsSubmitted: string
  issues: string
  nextDayPlan: string
  status: string
}

export interface TrainingDashboard {
  totalTrainees: number
  kaUserCount: number
  overallPassRate: number
  moduleStats: { module: string; examCount: number; passRate: number }[]
  attendanceRate: number
  documentCompletionRate: number
  goLiveReady: boolean
}

export interface Department {
  id: number; deptCode: string; deptName: string; parentId: number | null
  managerId: number | null; sortOrder: number; enabled: boolean
}

export interface EmployeeRecord {
  id: number; employeeCode: string; name: string; gender: string
  idCard: string; phone: string; email: string; deptId: number
  position: string; joinDate: string; enabled: boolean
}

export interface BankAccount {
  id: number; accountCode: string; accountName: string; accountType: string
  bankName: string; bankAccountNo: string; bankBranch: string
  currency: string; subjectCode: string; enabled: boolean
}

export interface StorageLocation {
  id: number; locationCode: string; locationName: string; warehouseId: number
  locationType: string; enabled: boolean
}

export interface AccountSubject {
  id: number; subjectCode: string; subjectName: string; parentCode: string
  subjectCategory: string; balanceDirection: string; auxiliaryAccounting: string
  isLeaf: boolean; enabled: boolean
}

export interface InventoryBalance {
  id: number; projectId: number; productId: number; warehouseId: number
  locationId: number | null; batchNo: string; inboundDate: string
  quantity: number; weight: number; packQuantity: number; costUnitPrice: number
  wholeUnits: number; oddUnits: number; costAmount: number; unitWeight: number
}

export interface CustomerBalance {
  id: number; projectId: number; customerId: number; docType: string; docNo: string
  docDate: string; receivableAmount: number; receivedAmount: number
  balance: number; balanceType: string; expectedDate: string; remark: string
}

export interface SupplierBalance {
  id: number; projectId: number; supplierId: number; balance: number; balanceType: string
  docType: string; docNo: string; docDate: string; remark: string
}

export interface AccountBalance {
  id: number; projectId: number; bankAccountId: number; currency: string
  openingBalance: number; remark: string
}

export interface SubjectBalance {
  id: number; projectId: number; subjectCode: string; subjectName: string
  debitBalance: number; creditBalance: number
}

export interface TrialBalance {
  projectId: number; totalDebit: number; totalCredit: number; balanced: boolean
}

export interface OtherReceivable {
  id: number; projectId: number; subjectCode: string; objectType: string
  objectId: number; objectName: string; summary: string; amount: number; occurDate: string
}

export interface OtherPayable {
  id: number; projectId: number; subjectCode: string; objectType: string
  objectId: number; objectName: string; summary: string; amount: number; occurDate: string
}

export interface InvoiceBalance {
  id: number; projectId: number; invoiceType: string; counterpartyId: number
  counterpartyName: string; docNo: string; productId: number; productName: string
  spec: string; material: string; quantity: number; unitPrice: number
  amount: number; taxRate: number; taxAmount: number; totalAmount: number; docDate: string
}

export interface ProjectPlan {
  id: number; projectId: number; planName: string; totalDays: number
  milestones: string; wbsItems: string; resources: string; risks: string; status: string
}

export interface RequiredCourse {
  id: number; industryType: string; courseModule: string; kaRequired: boolean; sortOrder: number
}

export interface SysUser {
  id: number
  username: string
  realName: string
  role: string
  phone: string
  email: string
}

export interface LoginVO {
  token: string
  username: string
  realName: string
  role: string
  expiresIn: number
}

export interface LlmProviderConfig {
  id: number
  providerName: string
  providerType: string
  apiEndpoint: string
  apiKey: string
  modelName: string
  maxTokens: number
  temperature: number
  enabled: boolean
}

export interface AgentConfig {
  id: number
  agentCode: string
  agentName: string
  description: string
  llmProviderId: number
  fallbackLlmProviderId: number | null
  promptTemplate: string
  ragEnabled: boolean
  ragCollectionName: string
  enabled: boolean
}

export interface ClientLoginVO {
  accessToken: string
  projectId: number
  projectName: string
  employeeName: string
  role: string
}

export interface QaSession {
  id: number
  projectId: number
  clientUserId: number
  title: string
  status: string
  messageCount: number
  createTime: string
  employeeName?: string
  projectName?: string
}

export interface QaMessage {
  id: number
  sessionId: number
  role: string
  content: string
  relatedModule: string
  relatedVideoUrl: string
  helpful: boolean | null
  createTime: string
}

export interface PmRecommendation {
  engineerId: number; engineerCode: string; name: string; level: string
  matchScore: number; matchReasons: string[]; riskNotes: string | null
  currentStatus: string; currentProjectCount: number; compositeScore: number
}
export interface MilestoneVO { name: string; dayOffset: number; deliverables: string }
export interface ScheduleSuggestion {
  recommendedStart: string; estimatedDurationDays: number; milestones: MilestoneVO[]
}
export interface DispatchResult {
  recommendedPms: PmRecommendation[]; scheduleSuggestion: ScheduleSuggestion
}

export interface GeneratedPlan {
  estimatedDurationDays: number; riskLevel: string
  milestones: { name: string; dayOffset: number; deliverables: string }[]
  wbsItems: { phase: string; taskName: string; startDay: number; endDay: number; responsible: string; deliverable: string }[]
  resourcePlan: { role: string; headcount: number; phase: string; skills: string }[]
  riskPlan: { riskName: string; riskLevel: string; impact: string; mitigation: string; isHighRisk: boolean }[]
  ganttData: { taskName: string; phase: string; startDay: number; endDay: number; progress: number; dependencies: string }[]
}
