export interface R<T> {
  code: number
  message: string
  data: T
}

export interface Project {
  id: number
  projectCode: string
  customerName: string
  industryType: string
  scale: string
  pmId: number
  status: string
  modules: string
  region: string
  startDate: string
  endDate: string
  remark: string
  createTime: string
}

export interface ProductCategory {
  id: number
  categoryCode: string
  categoryName: string
  parentId: number | null
  level: number
  sortOrder: number
  categoryGroup: string
  defaultUnit: string
  enabled: boolean
}

export interface Product {
  id: number
  productCode: string
  productName: string
  spec: string
  material: string
  steelMill: string
  surface: string
  categoryId: number
  unit: string
  pricingUnit: string
  taxRate: number
  enabled: boolean
  codeAutoGenerated: boolean
  createTime: string
}

export interface Customer {
  id: number
  customerCode: string
  fullName: string
  shortName: string
  customerType: string
  creditCode: string
  contact: string
  phone: string
  province: string
  city: string
  district: string
  address: string
  category: string
  settlementMethod: string
  creditLimit: number
  taxRate: number
  salesRepId: number
  enabled: boolean
  createTime: string
}

export interface ExamRecord {
  id: number
  projectId: number
  traineeId: number
  module: string
  examType: string
  score: number
  passed: boolean
  requiredCourse: boolean
  weakPoints: string
  retryOf: number | null
  examTime: string
}

export interface GoLiveCheck {
  projectId: number
  goLiveReady: boolean
  message: string
}

export type IndustryType = 'STEEL_TRADER' | 'STEEL_MILL' | 'PROCESSING_CENTER' | 'INTEGRATED_SERVICE'

export const IndustryTypeLabels: Record<IndustryType, string> = {
  STEEL_TRADER: '钢贸商',
  STEEL_MILL: '钢厂',
  PROCESSING_CENTER: '加工中心',
  INTEGRATED_SERVICE: '综合服务商',
}

export const ProjectStatusLabels: Record<string, string> = {
  PENDING: '待启动',
  RESEARCH: '调研中',
  PLAN: '计划中',
  TRAINING: '培训中',
  DATA_IMPORT: '数据导入',
  GO_LIVE: '上线中',
  FOLLOW_UP: '跟进辅助',
  DELIVERED: '已交付',
  AFTER_SALES: '售后阶段',
}

export interface CustomerProfile {
  id: number
  projectId: number
  companyName: string
  industryType: string
  businessModel: string
  tradeMode: string
  tradeScope: string
  mainBusiness: string
  totalProductionLines: number
  totalWarehouseCount: number
  totalWarehouseAreaSqm: number
  totalCraneCount: number
  monthlyVolume: number
  monthlyAmount: number
  totalStaff: number
  managementGoals: string
  processGoals: string
  efficiencyGoals: string
  riskControlGoals: string
}

export interface AccountSet {
  id: number
  projectId: number
  setName: string
  accountingSystem: string
  pricingMethod: string
  qtyDecimals: number
  wgtDecimals: number
  prcDecimals: number
  amtDecimals: number
  useWeight: boolean
  currency: string
  fiscalYearStart: number
  status: string
}

export interface DeliveryReport {
  id: number
  projectId: number
  reportType: string
  title: string
  trainingPassRate: number
  dataImportCompletionRate: number
  totalIssues: number
  resolvedIssues: number
  customerSatisfactionScore: number
  scheduleDeviationPercent: number
  documentCompletionRate: number
  overallScore: number
  aiComment: string
  status: string
  confirmedBy: string
  confirmedAt: string
}

export interface Engineer {
  id: number
  engineerCode: string
  name: string
  level: string
  skills: string
  currentStatus: string
  currentProjectId: number | null
  joinDate: string
  phone: string
  email: string
  compositeScore: number
  monthlyIdleRate: number
  monthlyProjectCount: number
}

export interface ProjectEvaluation {
  id: number
  projectId: number
  evaluatorId: number
  scheduleScore: number
  qualityScore: number
  csatScore: number
  processScore: number
  costScore: number
  pqiScore: number
  rating: string
  aiComment: string
}

export interface ServerProfile {
  id: number
  projectId: number
  serverName: string
  host: string
  port: number
  dbType: string
  dbName: string
  sslEnabled: boolean
  osType: string
  erpVersion: string
  apiBaseUrl: string
  status: string
  lastHealthCheck: string
  networkLatencyMs: number
}

export interface GoLiveCheckItem {
  id: number
  projectId: number
  category: string
  itemName: string
  description: string
  checkResult: string
  detail: string
  checkedAt: string
  checkedBy: string
}

export interface SimulationScene {
  id: number
  projectId: number
  sceneName: string
  sceneType: string
  description: string
  steps: string
  expectedResult: string
  actualResult: string
  status: string
  executedAt: string
  executedBy: string
  deviation: string
}

export const EngineerLevelLabels: Record<string, string> = {
  INTERN: '实习',
  JUNIOR: '初级实施',
  MIDDLE: '中级实施',
  SENIOR: '高级实施',
  PM: 'PM',
  SENIOR_PM: '高级PM',
  EXPERT_PM: '资深PM',
}

export const EngineerStatusLabels: Record<string, string> = {
  IDLE: '空闲',
  ON_PROJECT: '在项目',
  TRAINING: '培训中',
  LEAVE: '请假',
}

export const EvalRatingLabels: Record<string, string> = {
  EXCELLENT: '卓越',
  GOOD: '优良',
  QUALIFIED: '合格',
  NEEDS_IMPROVEMENT: '待改进',
  UNQUALIFIED: '不合格',
}

export const CheckResultLabels: Record<string, string> = {
  PASS: '通过',
  FAIL: '未通过',
  WARNING: '警告',
  UNCHECKED: '未检查',
}

export const SimulationStatusLabels: Record<string, string> = {
  PENDING: '待执行',
  RUNNING: '执行中',
  PASSED: '通过',
  FAILED: '未通过',
}
