export interface R<T> {
  code: number
  message: string
  data: T
}

export interface Project {
  id: number
  projectCode: string
  customerName: string
  industryType: string
  scale: string
  pmId: number
  status: string
  modules: string
  region: string
  startDate: string
  endDate: string
  remark: string
  createTime: string
}

export interface ProductCategory {
  id: number
  categoryCode: string
  categoryName: string
  parentId: number | null
  level: number
  sortOrder: number
  categoryGroup: string
  defaultUnit: string
  enabled: boolean
}

export interface Product {
  id: number
  productCode: string
  productName: string
  spec: string
  material: string
  steelMill: string
  surface: string
  categoryId: number
  unit: string
  pricingUnit: string
  taxRate: number
  enabled: boolean
  codeAutoGenerated: boolean
  createTime: string
}

export interface Customer {
  id: number
  customerCode: string
  fullName: string
  shortName: string
  customerType: string
  creditCode: string
  contact: string
  phone: string
  province: string
  city: string
  district: string
  address: string
  category: string
  settlementMethod: string
  creditLimit: number
  taxRate: number
  salesRepId: number
  enabled: boolean
  createTime: string
}

export interface ExamRecord {
  id: number
  projectId: number
  traineeId: number
  module: string
  examType: string
  score: number
  passed: boolean
  requiredCourse: boolean
  weakPoints: string
  retryOf: number | null
  examTime: string
}

export interface GoLiveCheck {
  projectId: number
  goLiveReady: boolean
  message: string
}

export type IndustryType = 'STEEL_TRADER' | 'STEEL_MILL' | 'PROCESSING_CENTER' | 'INTEGRATED_SERVICE'

export const IndustryTypeLabels: Record<IndustryType, string> = {
  STEEL_TRADER: '钢贸商',
  STEEL_MILL: '钢厂',
  PROCESSING_CENTER: '加工中心',
  INTEGRATED_SERVICE: '综合服务商',
}

export const ProjectStatusLabels: Record<string, string> = {
  PENDING: '待启动',
  RESEARCH: '调研中',
  PLAN: '计划中',
  TRAINING: '培训中',
  DATA_IMPORT: '数据导入',
  GO_LIVE: '上线中',
  FOLLOW_UP: '跟进辅助',
  DELIVERED: '已交付',
  AFTER_SALES: '售后阶段',
}
