package com.aimpl.domain.archive.entity;

import com.baomidou.mybatisplus.annotation.*;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@TableName("t_product")
public class Product {

    @TableId(type = IdType.AUTO)
    private Long id;

    /** 货品编码（有则保留，无则AI自动生成） */
    private String productCode;

    private String productName;

    private String spec;

    private String material;

    private String steelMill;

    private String surface;

    private Long categoryId;

    private String unit;

    private String pricingUnit;

    private BigDecimal theoreticalWeight;

    private BigDecimal taxRate;

    private Boolean enabled;

    /** 标记编码是否由系统自动生成 */
    private Boolean codeAutoGenerated;

    @TableField(fill = FieldFill.INSERT)
    private LocalDateTime createTime;

    @TableField(fill = FieldFill.INSERT_UPDATE)
    private LocalDateTime updateTime;

    @TableLogic
    private Integer deleted;
}
