<template>
  <div>
    <div class="page-header">
      <h2>货品档案</h2>
      <el-button type="primary" @click="showDialog = true">新增货品</el-button>
    </div>

    <div class="card">
      <el-table :data="products" stripe>
        <el-table-column prop="productCode" label="货品编码" width="160">
          <template #default="{ row }">
            {{ row.productCode }}
            <el-tag v-if="row.codeAutoGenerated" size="small" type="info" class="ml-1">自动</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="productName" label="品名" width="120" />
        <el-table-column prop="spec" label="规格" min-width="140" />
        <el-table-column prop="material" label="材质" width="90" />
        <el-table-column prop="steelMill" label="钢厂" width="120" />
        <el-table-column prop="unit" label="单位" width="60" />
        <el-table-column label="状态" width="80">
          <template #default="{ row }">
            <el-tag :type="row.enabled ? 'success' : 'danger'" size="small">
              {{ row.enabled ? '启用' : '停用' }}
            </el-tag>
          </template>
        </el-table-column>
      </el-table>
    </div>

    <el-dialog v-model="showDialog" title="新增货品" width="640px" destroy-on-close>
      <el-form ref="formRef" :model="form" :rules="rules" label-width="100px">
        <el-form-item label="货品编码" prop="productCode">
          <el-input v-model="form.productCode" placeholder="留空则系统自动生成" maxlength="40" />
          <div class="form-tip">不填写编码时，系统将根据品类+规格自动生成有序编码</div>
        </el-form-item>
        <el-form-item label="品名" prop="productName">
          <el-input v-model="form.productName" placeholder="如：热轧卷板" maxlength="60" />
        </el-form-item>
        <el-form-item label="规格" prop="spec">
          <el-input v-model="form.spec" placeholder="如：3.0*1250*C 或 20*40*1.5" maxlength="80" />
        </el-form-item>
        <el-form-item label="材质">
          <el-input v-model="form.material" placeholder="如：Q235B" maxlength="30" />
        </el-form-item>
        <el-form-item label="钢厂">
          <el-input v-model="form.steelMill" placeholder="如：宝钢" maxlength="60" />
        </el-form-item>
        <el-form-item label="货品类别" prop="categoryId">
          <el-input-number v-model="form.categoryId" :min="1" controls-position="right" placeholder="类别ID" />
        </el-form-item>
        <el-row :gutter="16">
          <el-col :span="12">
            <el-form-item label="计量单位">
              <el-input v-model="form.unit" placeholder="吨/件/张" maxlength="10" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="税率" prop="taxRate">
              <el-input-number v-model="form.taxRate" :min="0" :max="1" :step="0.01" :precision="2" controls-position="right" />
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
      <template #footer>
        <el-button @click="showDialog = false">取消</el-button>
        <el-button type="primary" :loading="submitting" @click="handleSubmit">确定</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import type { FormInstance } from 'element-plus'
import { ElMessage } from 'element-plus'
import { createProduct, listProducts } from '@/api/archive'
import type { Product } from '@/types'
import { required, maxLen, taxRateRule } from '@/utils/validators'

const products = ref<Product[]>([])
const showDialog = ref(false)
const submitting = ref(false)
const formRef = ref<FormInstance>()

const form = ref({
  productCode: '',
  productName: '',
  spec: '',
  material: '',
  steelMill: '',
  surface: '',
  categoryId: undefined as number | undefined,
  unit: '吨',
  pricingUnit: '',
  taxRate: 0.13,
})

const rules = {
  productName: [required('品名不能为空'), maxLen(60)],
  spec: [required('规格不能为空'), maxLen(80)],
  categoryId: [required('货品类别不能为空')],
  taxRate: [taxRateRule],
}

async function loadData() {
  const res = await listProducts()
  products.value = res.data.data
}

async function handleSubmit() {
  const valid = await formRef.value?.validate().catch(() => false)
  if (!valid) return

  submitting.value = true
  try {
    const payload = { ...form.value, productCode: form.value.productCode || undefined }
    await createProduct(payload as unknown as Record<string, unknown>)
    ElMessage.success('货品创建成功')
    showDialog.value = false
    await loadData()
  } finally {
    submitting.value = false
  }
}

onMounted(loadData)
</script>

<style scoped>
.form-tip {
  font-size: 12px;
  color: var(--text-secondary);
  margin-top: 4px;
  line-height: 1.4;
}
.ml-1 { margin-left: 6px; }
</style>
